### ISSUE TITLE
Make it possible to specify only one boundary for a heat map range

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#32] opened 2015-10-14 22:26 UTC
The other boundary should then default to the min or max value as appropriate.  Currently, if only one value is specified, it is simply ignored, which is counter-intuitive.

**Comment by thethirduniverse** [comment] 2015-11-13 21:09
If, say, `specMin` is empty and `specMax` is 10, so I should pass like this `specRange =  c(NULL,10)`

If on the ther hand `specMin` is 10 and `specMax` is empty, so I should pass like this `specRange =  c(10,NULL)`

Is that correct?

**Comment by ybukhman** [comment] 2015-11-13 21:26
Yes

**Comment by thethirduniverse** [comment] 2015-11-16 21:06
http://www.r-bloggers.com/r-na-vs-null/

According to this website, it seems that we can't put NULL inside a vector, but we can do that with NA. So I'll pass `c(NA, max)` and `c(min, NA)` instead

**Comment by ybukhman** [comment] 2015-11-16 21:24
Sounds good to me!

**Comment by thethirduniverse** [comment] 2015-11-20 20:29
Hi Yury I an **R label** is needed for this ticket to signal it is also an R issue.

R will throw and error when I pass it `c[1, NA]`

`Error: Heat map range must be numeric and finite. Bad range: 1-NA`

**Comment by amangpt777** [comment] 2015-11-22 01:30
Created one https://github.com/ybukhman/GCAT/issues/48 (without label though)  and fixed, sent pull request. Let me know if you face any issues post pull request is completed. Thanks!

**Comment by thethirduniverse** [comment] 2015-11-23 18:54
Hi Aman, if both of the ranges are blank, what should I pass? NA or c(NA, NA)?

**Comment by thethirduniverse** [comment] 2015-11-23 19:03
If I set specRange to c(1.0, NA), it will give me error like this:
`Error in gcat.output.main(fitted.well.array.master, out.prefix = "output", : Error in <pdf.by.plate>: Error in cut.default(x, breaks = breaks, include.lowest = T) : 'breaks' are not unique`

It I set totalRange to c(1.0, NA), the error will be like this:
`Error in setwd(old.wd) : character argument expected`

Am I passing the parameters wrong?

**Comment by amangpt777** [comment] 2015-11-23 21:37
For both ranges blank you can give c(NA, NA) and actually NA will also work. You can try giving it any of the both ways you want. 
For the second part I am not sure why it is giving you this error. For me it works fine if i give the values specified like yours. Let me check again, I will get back to you on this.

**Comment by amangpt777** [comment] 2015-11-23 22:35
Its a good catch Guanqing. I tested the functionality with nearby values like if max growth is 0.139 I was giving minimum value as 0.034 and that's why it worked for me. 
But if a user is specifying some minimum range value which is greater than the max growth in well then it will throw an error. I will discuss this with Yury and fix this and let you know.

**Comment by ybukhman** [comment] 2015-11-24 00:15
Not  sure what this is about.  Let's talk tomorrow.

**Comment by amangpt777** [comment] 2015-11-25 23:06
Hi Guanqing,

1. Can you pull the latest master branch and check now about setting the specRange to c(1.0, NA). It should throw a proper error message now. As I explained to you earlier, user should not provide the minimum value (i.e. 1.0 here) greater than the maximum actual value (for the sample input file the actual maximum value possible is 0.133 I guess). It was an existing issue in legacy system but is fixed now. Let me know if there are still some issues in the same. 
I need your help in testing that proper error messages are being passed from R to Rails.

2. For : """It I set totalRange to c(1.0, NA), the error will be like this: Error in setwd(old.wd) : character argument expected""". Can you show me how you are getting this error?

Thanks,
Aman

**Comment by thethirduniverse** [comment] 2015-11-30 18:40
1. I have tested it and it is displaying the error properly.
2. Strangely I am not able to reproduce this error as well. Maybe it was due to the same bug as the previous one? I'll let you know if I encounter it again.

Thanks!

**Closed** 2015-11-30 22:39 UTC
Labels: enhancement, Rails
